# Generated by Django 3.1.2 on 2020-12-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0005_auto_20201207_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='previouslocations',
            name='location_name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
